In [ ]:
#hide
import ndpretty

# Welcome to `ndpretty`

> Your little helper to display numpy ndarrays in a pretty table in Jupyter notebooks.

Jupyter notebooks are a great way to develop. `ndpretty` makes it even better for people who use numpy by providing nice formatting of `ndarray`s.

## Install

`pip install ndpretty`

## How to use

In [ ]:
#hide
import numpy as np

The default configuration is loaded as simply as this:

In [ ]:
ndpretty.default()

After this line has been exectued, all cell outputs that are `np.ndarray` or `torch.Tensor` are automatically formatted by ndpretty.

In [ ]:
a = np.random.rand(20, 30, 2)
a

20×30×2 float64 ndarray


interactive(children=(Text(value='[:, :, 0]', description='Slice:', placeholder='e.g. [:, :, 0]'), Output()), …

## Why?

Normally, `ndarray`s look like this in a Jupyter notebook:

In [ ]:
a = np.random.rand(20, 30, 2)
print(a)

[[[0.92987402 0.37964951]
  [0.71744738 0.67610855]
  [0.29951481 0.88342422]
  ...
  [0.58128952 0.34467292]
  [0.25793956 0.56561584]
  [0.11380439 0.53225802]]

 [[0.74660138 0.74797719]
  [0.29961368 0.95045383]
  [0.12346484 0.4300995 ]
  ...
  [0.37511978 0.75818852]
  [0.24318183 0.26340081]
  [0.43413628 0.1152024 ]]

 [[0.7719407  0.69951099]
  [0.67462352 0.86656649]
  [0.31217199 0.45763672]
  ...
  [0.46353269 0.13409251]
  [0.49566843 0.09770757]
  [0.32025045 0.7622831 ]]

 ...

 [[0.75372323 0.34762715]
  [0.22319648 0.04102715]
  [0.93972069 0.29059917]
  ...
  [0.25051261 0.38179117]
  [0.79411028 0.31214728]
  [0.75248059 0.39229262]]

 [[0.53900449 0.2093348 ]
  [0.70453061 0.09488001]
  [0.05090444 0.64068512]
  ...
  [0.97843977 0.81601184]
  [0.27656764 0.19184449]
  [0.99781007 0.35601416]]

 [[0.65816237 0.59816489]
  [0.40112403 0.06420206]
  [0.97024711 0.61586378]
  ...
  [0.46107372 0.27605212]
  [0.58429168 0.50894938]
  [0.73329027 0.03234803]]]


At least to me, that's quite hard to read. Using `ndpretty` they look like this:

In [ ]:
np.random.rand(10, 20)

10×20 float64 ndarray


## Author

Patrick Deutschmann ([patrick@deutschmann.xyz](mailto:patrick@deutschmann.xyz))