In [ ]:
#hide
import ndpretty

# Welcome to `ndpretty`

> Your little helper to display numpy ndarrays in a pretty table in Jupyter notebooks.

Jupyter notebooks are a great way to develop. `ndpretty` makes it even better for people who use numpy by providing nice formatting of `ndarray`s.

## Install

`pip install ndpretty`

## How to use

In [ ]:
#hide
import numpy as np

The default configuration is loaded as simply as this:

In [ ]:
ndpretty.default()

After this line has been exectued, all cell outputs that are `np.ndarray` or `torch.Tensor` are automatically formatted by ndpretty.

In [ ]:
a = np.random.rand(20, 30, 2)
a

20×30×2 float64 ndarray


interactive(children=(Text(value='[:, :, 0]', description='Slice:', placeholder='e.g. [:, :, 0]'), Output()), …

## Why?

Normally, `ndarray`s look like this in a Jupyter notebook:

In [ ]:
a = np.random.rand(20, 30, 2)
print(a)

[[[0.67332527 0.34687068]
  [0.38336068 0.34281941]
  [0.1953115  0.2203909 ]
  ...
  [0.41523347 0.14889802]
  [0.35095522 0.27271219]
  [0.93926387 0.83926031]]

 [[0.19346472 0.07249269]
  [0.55515394 0.25984324]
  [0.05044609 0.07408243]
  ...
  [0.22227792 0.93505193]
  [0.13283968 0.36381562]
  [0.78231665 0.40666018]]

 [[0.60423577 0.56197322]
  [0.264191   0.13435128]
  [0.26342234 0.43812004]
  ...
  [0.91436535 0.73497115]
  [0.51160691 0.4990356 ]
  [0.03899651 0.31745117]]

 ...

 [[0.89763993 0.74951795]
  [0.1901834  0.18405086]
  [0.90574303 0.67517041]
  ...
  [0.38670804 0.92472416]
  [0.4938217  0.6947183 ]
  [0.0836607  0.93746114]]

 [[0.25596595 0.90138221]
  [0.47579009 0.62427661]
  [0.88145006 0.20649818]
  ...
  [0.62222373 0.83292506]
  [0.6138533  0.1446508 ]
  [0.72526005 0.71392611]]

 [[0.07450451 0.84449197]
  [0.04629121 0.30654866]
  [0.51159759 0.94059547]
  ...
  [0.11555924 0.28475242]
  [0.40253806 0.34814258]
  [0.75509527 0.95187282]]]


At least to me, that's quite hard to read. Using `ndpretty` they look like this:

In [ ]:
np.random.rand(10, 20)

10×20 float64 ndarray


## Author

Patrick Deutschmann ([patrick@deutschmann.xyz](mailto:patrick@deutschmann.xyz))